# Name of your application. Used to uniquely configure containers.
service: activity_pub_app

# Name of the container image.
image: mbajur/activity_pub_app

volumes:
  - "/home/app/activity_pub_app-cache:/app/tmp/cache"
  - "/home/app/activity_pub_app-shared:/app/shared"
  - "/home/app/activity_pub_app-storage:/app/storage"

servers:
  web:
    hosts:
      - 209.38.211.5
    cmd: bundle exec thrust bin/rails server

  job:
    hosts:
      - 209.38.211.5
    cmd: bundle exec good_job

registry:
  server: ghcr.io
  username: mbajur

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    HOSTNAME: aptest2.mbajur.com
    APP_DOMAIN: aptest2.mbajur.com
    DB_HOST: activity_pub_app-db
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - POSTGRES_PASSWORD
    - RAILS_MASTER_KEY

builder:
  arch: amd64

accessories:
  db:
    image: postgres:15
    host: 209.38.211.5
    port: 5432
    env:
      clear:
        POSTGRES_USER: "activity_pub_app"
        POSTGRES_DB: 'activity_pub_app_production'
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data

proxy:
  ssl: true
  host: aptest2.mbajur.com
